[package]
name = "catalog-store"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
catalog-core = { path = "../catalog-core" }
anyhow.workspace = true
arrow-array.workspace = true
arrow-schema.workspace = true
chrono.workspace = true
futures.workspace = true
lance.workspace = true
object_store.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
