/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TablesIndexRouteImport } from './routes/tables.index'
import { Route as NamespacesIndexRouteImport } from './routes/namespaces.index'
import { Route as NamespacesNsRouteImport } from './routes/namespaces.$ns'
import { Route as TablesTableIdIndexRouteImport } from './routes/tables.$tableId.index'
import { Route as TablesTableIdVersionsVersionIdRouteImport } from './routes/tables.$tableId.versions.$versionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesIndexRoute = TablesIndexRouteImport.update({
  id: '/tables/',
  path: '/tables/',
  getParentRoute: () => rootRouteImport,
} as any)
const NamespacesIndexRoute = NamespacesIndexRouteImport.update({
  id: '/namespaces/',
  path: '/namespaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const NamespacesNsRoute = NamespacesNsRouteImport.update({
  id: '/namespaces/$ns',
  path: '/namespaces/$ns',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesTableIdIndexRoute = TablesTableIdIndexRouteImport.update({
  id: '/tables/$tableId/',
  path: '/tables/$tableId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesTableIdVersionsVersionIdRoute =
  TablesTableIdVersionsVersionIdRouteImport.update({
    id: '/tables/$tableId/versions/$versionId',
    path: '/tables/$tableId/versions/$versionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/namespaces/$ns': typeof NamespacesNsRoute
  '/namespaces/': typeof NamespacesIndexRoute
  '/tables/': typeof TablesIndexRoute
  '/tables/$tableId/': typeof TablesTableIdIndexRoute
  '/tables/$tableId/versions/$versionId': typeof TablesTableIdVersionsVersionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/namespaces/$ns': typeof NamespacesNsRoute
  '/namespaces': typeof NamespacesIndexRoute
  '/tables': typeof TablesIndexRoute
  '/tables/$tableId': typeof TablesTableIdIndexRoute
  '/tables/$tableId/versions/$versionId': typeof TablesTableIdVersionsVersionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/namespaces/$ns': typeof NamespacesNsRoute
  '/namespaces/': typeof NamespacesIndexRoute
  '/tables/': typeof TablesIndexRoute
  '/tables/$tableId/': typeof TablesTableIdIndexRoute
  '/tables/$tableId/versions/$versionId': typeof TablesTableIdVersionsVersionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/namespaces/$ns'
    | '/namespaces/'
    | '/tables/'
    | '/tables/$tableId/'
    | '/tables/$tableId/versions/$versionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/namespaces/$ns'
    | '/namespaces'
    | '/tables'
    | '/tables/$tableId'
    | '/tables/$tableId/versions/$versionId'
  id:
    | '__root__'
    | '/'
    | '/namespaces/$ns'
    | '/namespaces/'
    | '/tables/'
    | '/tables/$tableId/'
    | '/tables/$tableId/versions/$versionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NamespacesNsRoute: typeof NamespacesNsRoute
  NamespacesIndexRoute: typeof NamespacesIndexRoute
  TablesIndexRoute: typeof TablesIndexRoute
  TablesTableIdIndexRoute: typeof TablesTableIdIndexRoute
  TablesTableIdVersionsVersionIdRoute: typeof TablesTableIdVersionsVersionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tables/': {
      id: '/tables/'
      path: '/tables'
      fullPath: '/tables/'
      preLoaderRoute: typeof TablesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/namespaces/': {
      id: '/namespaces/'
      path: '/namespaces'
      fullPath: '/namespaces/'
      preLoaderRoute: typeof NamespacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/namespaces/$ns': {
      id: '/namespaces/$ns'
      path: '/namespaces/$ns'
      fullPath: '/namespaces/$ns'
      preLoaderRoute: typeof NamespacesNsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tables/$tableId/': {
      id: '/tables/$tableId/'
      path: '/tables/$tableId'
      fullPath: '/tables/$tableId/'
      preLoaderRoute: typeof TablesTableIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tables/$tableId/versions/$versionId': {
      id: '/tables/$tableId/versions/$versionId'
      path: '/tables/$tableId/versions/$versionId'
      fullPath: '/tables/$tableId/versions/$versionId'
      preLoaderRoute: typeof TablesTableIdVersionsVersionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NamespacesNsRoute: NamespacesNsRoute,
  NamespacesIndexRoute: NamespacesIndexRoute,
  TablesIndexRoute: TablesIndexRoute,
  TablesTableIdIndexRoute: TablesTableIdIndexRoute,
  TablesTableIdVersionsVersionIdRoute: TablesTableIdVersionsVersionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
