---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - minio.yaml
  - fixture-job.yaml

patches:
  # Replace ConfigMap values with local (MinIO) endpoints and debug settings.
  - path: configmap-patch.yaml
  # Reduce replicas to 1 and inject MinIO credentials.
  - path: catalog-api-patch.yaml
